name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_cpu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Dependencies
      run: |
        sudo apt update
        sudo apt-get install -y build-essential cmake curl git libopencv-dev
        git submodule update --init --recursive

    - name: Install RETINIFY
      run: |
        git clone https://github.com/retinify/retinify.git
        cd retinify
        ./build.sh --install --cpu

    - name: Build Example
      run: |
        mkdir build
        cd build
        cmake ..
        make
